blog/urls.py
import imp
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('posts.urls', namespace='blog'))
]



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from .views import delete_post, post_list, post_detail, new_post, edit_post, delete_post

app_name = 'posts'

urlpatterns = [
    path('', post_list, name='post_list'),
    path('<int:id>', post_detail, name='post_detail'),
    path('<int:id>/edit', edit_post, name='post_edit'),
    path('<int:id>/delete', delete_post, name='post_delete'),
    path('new', new_post, name='post_new'),
]

posts/models.py
from distutils.command.upload import upload
from operator import mod
from turtle import title
from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post_user')
    title = models.CharField(max_length=100)
    content = models.TextField(max_length=5000)
    active = models.BooleanField(default=False)
    image = models.ImageField(upload_to='posts/')
    
    
    
    def __str__(self):
        return self.title

posts/forms.py
from django import forms
from .models import Post

class Postform(forms.ModelForm):
    class Meta:
        model = Post
        #fields  = '__all__'
        #fields = ['title', 'content', 'active', 'image']
        exclude = ['author']
        

posts/views.py
from django.shortcuts import render, redirect
from .models import Post
from .forms import Postform
from django.urls import reverse

def post_list(request):
    objects = Post.objects.all()
    return render(request, 'posts/post_list.html', {'posts':objects})

def post_detail(request, id):
    single = Post.objects.get(id=id)
    return render(request, 'posts/post_detail.html', {'post':single})

def new_post(request):
    if request.method == 'POST':
        form = Postform(request.POST, request.FILES)
        if form.is_valid():
            myform = form.save(commit=False)
            myform.author = request.user
            myform.save()
            return redirect(reverse('blog:post_list'))
    else:
        form = Postform()
    return render(request, 'posts/new.html', {'form':form})

def edit_post(request, id):
    single = Post.objects.get(id=id)
    if request.method == 'POST':
        form = Postform(request.POST, request.FILES, instance=single)
        if form.is_valid():
            form.save()
    else:
        form = Postform(instance=single)
    return render(request, 'posts/edit.html', {'form':form})

def delete_post(request, id):
    single = Post.objects.get(id=id)
    single.delete()
    return redirect(reverse('blog:post_list'))#/blog/

posts/templates/posts/edit.html
<h1>Edit New Post</h1>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form}}
    <input type="submit" value="Save">
</form>
<hr>
<a href="{%url 'blog:post_list'%}">Home</a>

posts/templates/posts/new.html
<h1>Create New Post</h1>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form}}
    <input type="submit" value="Create">
</form>
<hr>
<a href="{%url 'blog:post_list'%}">Home</a>

posts/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block body %}
    <div class="main-content">
        <!-- start of mobile-nav -->
<header class="mobile-nav pt-4">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-6">
                <a href="index.html">
                    <img src="images/logo.png" alt="">
                </a>
            </div>
            <div class="col-6 text-right">
                <button class="nav-toggle bg-transparent border text-white">
                    <span class="fas fa-bars"></span>
                </button>
            </div>
        </div>
    </div>
</header>
<div class="nav-toggle-overlay"></div>
<!-- end of mobile-nav -->

            <div class="container py-4 my-5">
                <div class="row">
    <div class="col-lg-5 col-md-8">
        <form class="search-form" action="#">
            <div class="input-group">
                <input type="search" class="form-control bg-transparent shadow-none rounded-0" placeholder="Search here">
                <div class="input-group-append">
                    <button class="btn" type="submit">
                        <span class="fas fa-search"></span>
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
                
                <div class="row justify-content-between">
                    <div class="col-lg-10">
                        <img class="img-fluid" src="images/post/post-single/01.png" alt="">
                        <h1 class="text-white add-letter-space mt-4">{{post}}</h1>
                        <ul class="post-meta mt-3 mb-4">
                            <li class="d-inline-block mr-3">
                                <span class="fas fa-clock text-primary"></span>
                                <a class="ml-1" href="#">24 April, 2016</a>
                            </li>
                            <li class="d-inline-block">
                                <span class="fas fa-list-alt text-primary"></span>
                                <a class="ml-1" href="#">Photography</a>
                            </li>
                        </ul>

                        <p>
                             {{post.content}}
                        </p>
                        </div>
                        
                    </div>
                </div>
            </div>


{% endblock body %}

posts/templates/posts/post_detail2.html
<h1>Post Detail</h1>

<h2>{{post}}</h2>
<p>{{post.content}}</p>
<img src="{{post.image.url}}" alt="">
<hr>
<a href="{%url 'blog:post_edit' post.id%}">Edit Post</a>
<br>
<a href="{%url 'blog:post_delete' post.id%}">Delete Post</a>
<hr>
<a href="{%url 'blog:post_list'%}">Home</a>

posts/templates/posts/post_list.html
{% extends 'base.html' %}

{% block body %}
<div class="main-content">
    <!-- start of mobile-nav -->
<header class="mobile-nav pt-4">
<div class="container">
    <div class="row align-items-center">
        <div class="col-6">
            <a href="index.html">
                <img src="images/logo.png" alt="">
            </a>
        </div>
        <div class="col-6 text-right">
            <button class="nav-toggle bg-transparent border text-white">
                <span class="fas fa-bars"></span>
            </button>
        </div>
    </div>
</div>
</header>
<div class="nav-toggle-overlay"></div>
<!-- end of mobile-nav -->

    <div class="container pt-4 mt-5">
        <div class="row justify-content-between">
            <div class="col-lg-7">
                {%for post in posts%}
                <div class="card post-item bg-transparent border-0 mb-5">
                    <a href="post-details.html">
                        <img class="card-img-top rounded-0" src="images/post/post-lg/01.png" alt="">
                    </a>
                    <div class="card-body px-0">
                        <h2 class="card-title">
                            <a class="text-white opacity-75-onHover" href="{%url 'blog:post_detail' post.id%}">{{post}}</a>
                        </h2>
                        <ul class="post-meta mt-3">
                            <li class="d-inline-block mr-3">
                                <span class="fas fa-clock text-primary"></span>
                                <a class="ml-1" href="#">24 April, 2016</a>
                            </li>
                            <li class="d-inline-block">
                                <span class="fas fa-list-alt text-primary"></span>
                                <a class="ml-1" href="#">Photography</a>
                            </li>
                        </ul>
                        <p class="card-text my-4">{{post.content}}</p>
                        <a href="{%url 'blog:post_detail' post.id%}" class="btn btn-primary">Read More <img src="images/arrow-right.png" alt=""></a>
                    </div>
                </div>
                {% endfor %}
                <!-- end of post-item -->
            </div>
            <div class="col-lg-4 col-md-5">
                <div class="widget text-center">
                    <img class="author-thumb-sm rounded-circle d-block mx-auto" src="images/author-sm.png" alt="">
                    <h2 class="widget-title text-white d-inline-block mt-4">About Me</h2>
                    <p class="mt-4">Lorem ipsum dolor sit coectetur adiing elit. Tincidunfywjt leo mi, viearra urna. Arcu ve isus, condimentum ut vulpate cursus por turpis.</p>
                    <ul class="list-inline mt-3">
                        <li class="list-inline-item">
                            <a href="#!" class="text-white text-primary-onHover p-2">
                                <span class="fab fa-twitter"></span>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#!" class="text-white text-primary-onHover p-2">
                                <span class="fab fa-facebook-f"></span>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#!" class="text-white text-primary-onHover p-2">
                                <span class="fab fa-instagram"></span>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#!" class="text-white text-primary-onHover p-2">
                                <span class="fab fa-linkedin-in"></span>
                            </a>
                        </li>
                    </ul>
                </div>
                <!-- end of author-widget -->

                <div class="widget bg-dark p-4 text-center">
                    <h2 class="widget-title text-white d-inline-block mt-4">Subscribe Blog</h2>
                    <p class="mt-4">Lorem ipsum dolor sit coectetur elit. Tincidu nfywjt leo mi, urna. Arcu ve isus, condimentum ut vulpate cursus por.</p>
                    <form action="#">
                        <div class="form-group">
                            <input type="email" class="form-control bg-transparent rounded-0 my-4" placeholder="Your Email Address">
                            <button class="btn btn-primary">Subscribe Now <img src="images/arrow-right.png" alt=""></button>
                        </div>
                    </form>
                </div>
                <!-- end of subscription-widget -->

                <div class="widget">
                    <div class="mb-5 text-center">
                        <h2 class="widget-title text-white d-inline-block">Featured Posts</h2>
                    </div>
                    <div class="card post-item bg-transparent border-0 mb-5">
                        <a href="post-details.html">
                            <img class="card-img-top rounded-0" src="images/post/post-sm/01.png" alt="">
                        </a>
                        <div class="card-body px-0">
                            <h2 class="card-title">
                                <a class="text-white opacity-75-onHover" href="post-details.html">Excepteur ado Do minimal duis laborum Fugiat ea</a>
                            </h2>
                            <ul class="post-meta mt-3 mb-4">
                                <li class="d-inline-block mr-3">
                                    <span class="fas fa-clock text-primary"></span>
                                    <a class="ml-1" href="#">24 April, 2016</a>
                                </li>
                                <li class="d-inline-block">
                                    <span class="fas fa-list-alt text-primary"></span>
                                    <a class="ml-1" href="#">Photography</a>
                                </li>
                            </ul>
                            <a href="post-details.html" class="btn btn-primary">Read More <img src="images/arrow-right.png" alt=""></a>
                        </div>
                    </div>
                    <!-- end of widget-post-item -->
                    <div class="card post-item bg-transparent border-0 mb-5">
                        <a href="post-details.html">
                            <img class="card-img-top rounded-0" src="images/post/post-sm/02.png" alt="">
                        </a>
                        <div class="card-body px-0">
                            <h2 class="card-title">
                                <a class="text-white opacity-75-onHover" href="post-details.html">Excepteur ado Do minimal duis laborum Fugiat ea</a>
                            </h2>
                            <ul class="post-meta mt-3 mb-4">
                                <li class="d-inline-block mr-3">
                                    <span class="fas fa-clock text-primary"></span>
                                    <a class="ml-1" href="#">24 April, 2016</a>
                                </li>
                                <li class="d-inline-block">
                                    <span class="fas fa-list-alt text-primary"></span>
                                    <a class="ml-1" href="#">Photography</a>
                                </li>
                            </ul>
                            <a href="post-details.html" class="btn btn-primary">Read More <img src="images/arrow-right.png" alt=""></a>
                        </div>
                    </div>
                    <!-- end of widget-post-item -->
                </div>
                <!-- end of post-items widget -->
            </div>
        </div>
    </div>

    <!-- start of footer -->
<footer class="bg-dark">
<div class="container">
    <div class="row text-center">
        <div class="col-lg-3 col-sm-6 mb-5">
            <h5 class="font-primary text-white mb-4">Inspirations</h5>
            <ul class="list-unstyled">
                <li><a href="#!">Privacy State</a></li>
                <li><a href="#!">Privacy</a></li>
                <li><a href="#!">State</a></li>
                <li><a href="#!">Privacy</a></li>
            </ul>
        </div>
        <div class="col-lg-3 col-sm-6 mb-5">
            <h5 class="font-primary text-white mb-4">Templates</h5>
            <ul class="list-unstyled">
                <li><a href="#!">Privacy State</a></li>
                <li><a href="#!">Privacy</a></li>
                <li><a href="#!">State</a></li>
                <li><a href="#!">Privacy</a></li>
            </ul>
        </div>
        <div class="col-lg-3 col-sm-6 mb-5">
            <h5 class="font-primary text-white mb-4">Resource</h5>
            <ul class="list-unstyled">
                <li><a href="#!">Privacy State</a></li>
                <li><a href="#!">Privacy</a></li>
                <li><a href="#!">State</a></li>
                <li><a href="#!">Privacy</a></li>
            </ul>
        </div>
        <div class="col-lg-3 col-sm-6 mb-5">
            <h5 class="font-primary text-white mb-4">Company</h5>
            <ul class="list-unstyled">
                <li><a href="#!">Privacy State</a></li>
                <li><a href="#!">Privacy</a></li>
                <li><a href="#!">State</a></li>
                <li><a href="#!">Privacy</a></li>
            </ul>
        </div>
    </div>
</div>
</footer>
<!-- end of footer -->
</div>
{% endblock body %}

posts/templates/posts/posts.html
<h1>Blog</h1>

<a href="{%url 'blog:post_new'%}">Create new post</a>
<hr>

{%for post in posts%}

    <h2><a href="{%url 'blog:post_detail' post.id%}">{{post}}</a></h2>

    {% endfor %}

templates/base.html
{% load static %}
<!DOCTYPE html>

<!--
 // WEBSITE: https://themefisher.com
 // TWITTER: https://twitter.com/themefisher
 // FACEBOOK: https://www.facebook.com/themefisher
 // GITHUB: https://github.com/themefisher/
-->

<html>
<head>
    <meta charset="utf-8">
    <title>Galaxy - Personal Blog Template</title>

    <!-- mobile responsive meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!-- ** Plugins Needed for the Project ** -->
    <!-- Bootstrap -->
    <link rel="stylesheet" href="{% static 'plugins/bootstrap/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/fontawesome/css/all.css' %}">

    <!-- Main Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

    <!--Favicon-->
    <link rel="shortcut icon" href="images/favicon.png" type="image/x-icon">
    <link rel="icon" href="images/favicon.png" type="image/x-icon">

</head>
<body>
    <!-- START preloader-wrapper -->
    <div class="preloader-wrapper">
        <div class="preloader-inner">
            <div class="spinner-border text-red"></div>
        </div>
    </div>
    <!-- END preloader-wrapper -->
    
    <!-- START main-wrapper -->
    <section class="d-flex">
  
<!-- start of sidenav -->
<aside><div class="sidenav position-sticky d-flex flex-column justify-content-between">
    <a class="navbar-brand" href="index.html" class="logo">
        <img src="images/logo.png" alt="">
    </a>
    <!-- end of navbar-brand -->

    <div class="navbar navbar-dark my-4 p-0 font-primary">
        <ul class="navbar-nav w-100">
            <li class="nav-item active">
                <a class="nav-link text-white px-0 pt-0" href="index.html">Home</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link text-white px-0" href="about.html">About</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link text-white px-0" href="contact.html">Contact</a>
            </li>
            <li class="nav-item  accordion">
                <div id="drop-menu" class="drop-menu collapse">
                    <a class="d-block " href="index-2.html">Home 2</a>
                    <a class="d-block " href="category.html">Category</a>
                    <a class="d-block " href="post-details.html">Post Details</a>
                    <a class="d-block " href="privacy.html">Privacy &amp; Policy</a>
                </div>
                <a class="nav-link text-white" href="#!" role="button" data-toggle="collapse" data-target="#drop-menu" aria-expanded="false" aria-controls="drop-menu">Pages</a>
            </li>
            <li class="nav-item mt-3">
                <select class="custom-select bg-transparent rounded-0 text-white shadow-none" id="pick-lang">
                    <option selected value="en">English</option>
                    <option value="fr">French</option>
                </select>
            </li>
        </ul>
    </div>
    <!-- end of navbar -->

    <ul class="list-inline nml-2">
        <li class="list-inline-item">
            <a href="#!" class="text-white text-red-onHover pr-2">
                <span class="fab fa-twitter"></span>
            </a>
        </li>
        <li class="list-inline-item">
            <a href="#!" class="text-white text-red-onHover p-2">
                <span class="fab fa-facebook-f"></span>
            </a>
        </li>
        <li class="list-inline-item">
            <a href="#!" class="text-white text-red-onHover p-2">
                <span class="fab fa-instagram"></span>
            </a>
        </li>
        <li class="list-inline-item">
            <a href="#!" class="text-white text-red-onHover p-2">
                <span class="fab fa-linkedin-in"></span>
            </a>
        </li>
    </ul>
    <!-- end of social-links -->
</div></aside>
<!-- end of sidenav -->
    {% block body %}

    {% endblock body %}

    </section>
    <!-- END main-wrapper -->

    <!-- All JS Files -->
    <script src="{% static 'plugins/jQuery/jquery.min.js' %}"></script>
    <script src="{% static 'plugins/bootstrap/bootstrap.min.js' %}"></script>

    <!-- Main Script -->
    <script src="{% static 'js/script.js' %}"></script>
</body>
</html>